### ISSUE TITLE
Question: use case in "local" cloud

### ISSUE THREAD

**Issue by goofy2k** [bartbutenaers/node-red-contrib-drawsvg#1]
Hi Bart,  you have some pretty cool stuff here.  I installed the cloud-based version on  a Raspberry Pi and I am starting to discover all the nice things !   Later I discovered this local version. As it takes quite some storage I am wondering if it is possible that I install the local version on my NAS and access that service from my Raspberry Pi as a "local" cloud service?

Thanks,
Fred

**Comment by bartbutenaers** [comment]
Hi Fred,
If you have Node-RED running on your NAS, then you can of course run this node on your NAS.  Is that what you mean?
Or you can run a webserver on your NAS, and make the static DrawSvg resources (contained inside [edrawsvg_edrawsvg.zip](https://github.com/bartbutenaers/node-red-contrib-drawsvg/blob/master/lib/edrawsvg_edrawsvg.zip)) public available that way.  
Bart

**Comment by goofy2k** [comment]
Just to clearify: I have Nodered running on my NAS  as well as on the Raspberry Pi.  Can the Raspberry Pi use the service from the NAS? I expect that I have to install the local version on the NAS and the cloud-based version on the Pi.  Can I then point the URL in the settings on the NAS URL in stead of on drawsvg.org  ?  I'll have a look on your zip file .....

**Comment by bartbutenaers** [comment]
Do this:
1. Install the node-red-contrib-drawsvg on your NAS.
2. Now drawsvg should be available via http://your-nas_ip:1880/drawsvg_local/edrawsvg.html (or https)
3. Use that url in the config screen of the node-red-contrib-ui-svg nodes, which are running on your raspberry.

So instead of using the cloud service (hosted at https://www.drawsvg.org/drawsvg.html), you now have a local Drawsvg service running on your NAS...

**Comment by goofy2k** [comment]
OK, thanks! I'll give that a try.

**Comment by goofy2k** [comment]
This works fine. The editor appears on my Pi !

One small issue: the icons in the DRAW-SVG Tools menu (Draw,  Meme maker, Photo to SVG ....) are missing
![Capture](https://user-images.githubusercontent.com/26250702/99308597-79c32f80-2858-11eb-84a4-e78f9fb35dec.JPG)

**Comment by goofy2k** [comment]
Everything running OK. I found this package when I was looking for ways to
do drawing on the dashboard. Maybe you have a tip for that? If there is a
node for this, I don't have to code it myself in e.g. the dashboard
template node (using HTML canvas)

Fred

Op ma 16 nov. 2020 18:20 schreef bartbutenaers <notifications@github.com>:
