### ISSUE TITLE
Question, Dynamics update digram from Node Red. 

### ISSUE THREAD

**Issue by edperry** [bartbutenaers/node-red-contrib-drawsvg#2]
Is it possible to intereract with the Diagrams you build with this editor?

Say for example, I wanted to have something flash red when the door opened? 

or maybe want to dynamically add an element say when a PC joins my Wifi network?

**Comment by bartbutenaers** [comment]
Hi @edperry,
You have to use ***node-red-contrib-ui-svg*** to do that.  In the config screen of that node, you have a button to open the  Drawsvg editor: by default the Drawsvg cloud service, or your local Drawsvg service (which you can host via this node-red-contrib-drawsvg  node).
Bart
